[project]
name = "pearprogramming"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "python-dotenv>=0.21.0",
    "fastapi>=0.120.4",
    "langchain>=1.0.3",
    "langchain-openai>=1.0.1",
    "pydantic>=2.10.6,<3",
    "uvicorn>=0.38.0",
]
